### ISSUE TITLE
[FEATURE] api 응답 획일화 작업 

### ISSUE THREAD

**Issue by heewoong-ahn** [DevKor-github/IEUM-back#20]
## Description 

백엔드에서 응답을 프론트로 전달 할 때, 정상 응답일 때와 에러가 발생했을 때 규격화된 응답을 반환해 프론트에서의 작업을 수월하게 하기 위함. 

## Todos

- 정상 응답 interceptor 적용
- 에러 응답 filter 적용 

## ETC
이 외에도 고려할 사항이 있다면 작성해주세요.

**Comment by steadfastree** [comment]
이거 희웅님이 하실껀가여
제가할랫는데

**Comment by steadfastree** [comment]
일단 해보시구 애매한 부분 잇으면 공유주세요 리뷰하면서 같이해바여
