### ISSUE TITLE
[BUG] 웹 장소 리스트 페이지네이션 수정

### ISSUE THREAD

**Issue by steadfastree** [DevKor-github/IEUM-back#25]
## Description
웹에서 커서 기반 페이지네이션 + 무한 스크롤을 통해 페이지네이션을 구현하려고 하였으나, 다음 페이지를 한 번 호출한 뒤로는 같은 페이지만 계속 리턴되는 문제 발생

## To Reproduce
다음 장소 리스트를 요청하는 경우 요청 cursor_id가 아닌 다음 cursor_id가 응답으로 와야하지만 응답으로 요청 cursor_id가 동일하게 들어옴

이로인하여 같은 page가 동일하게 요청되어 동일 장소가 반복되서 보이는 현상 발생

api.ieum.devkor.club/instagram/collections/so_odeng?cusorId=66&region=

## Expected behavior
다음 요청 가능 페이지가 존재하는 경우 요청 cursor_id와 다음 검색 cursor_id는 다른 값을 가져야하며, 요청 cursor_id와 다음 검색 cursor_id가 같은 경우에는 hasNextPage = false 이어야할 것으로 보임

## Screenshots OR Logs
<img width="550" alt="Untitled" src="https://github.com/DevKor-github/IEUM-back/assets/109478362/559e3944-33ae-4ee1-b8ba-cfb08ae87e9e">

## ETC
x

**Comment by steadfastree** [comment]
이슈 작성 후 BE에서 확인하였으나 정상 작동하는 것으로 보여서 해결 보류함

**Comment by heewoong-ahn** [comment]
프론트 호출 문제였나요?

**Comment by steadfastree** [comment]
@heewoong-ahn Swagger상에서 확인해봤을 때는 정상 작동하는 것으로 보여서 서버 단에선 무슨 문제인지 파악이 어렵네용

**Comment by steadfastree** [comment]
API 문제는 아닌 것 같네요. 이슈 닫겠습니다
